1:
numberslist = []
numberofnumbers = int(input("How many numbers do you have? Enter only positive integers: "))
i = 0 
evennum = []
oddnum = []
while i < numberofnumbers:
    number = input("What is the number? ")
    numberslist.append(number)
    i = i + 1
    if number % 2 == 0:
        evennum.append(number)
    if number % 2 != 0:
        oddnum.append(number)
print("")
print("Your list is " + str(numberslist))
print("The even numbers are " + str(evennum))
print("The odd numbers are " + str(oddnum))

#2:
numlist = []
numberinput = int(input("How many numbers are there: "))
i = 0
while i < numberinput:
    numbers = input("What are the numbers? ")
    numlist.append(numbers)
    i = i + 1
j = len(numlist)
while j > -1:
    j = j - 1
    if numlist[j] == numlist[j - 1]:
        del numlist[j]
print("All duplicates have been removed from the list, your new list is " + str(numlist))        


#3:
numlist = []
numberinput = int(input("How many numbers are there: "))
i = 0
while i < numberinput:
    numbers = input("What are the numbers? ")
    numlist.append(numbers)
    i = i + 1
j = len(numlist) - 1
revlist = []
while j > -1:
    revlist.append(numlist[j])
    j = j - 1
print("Your reversed list is " + str(revlist))
#4:
numlist = []
numberinput = int(input("How many numbers are there: "))
i = 0
for n in range(numberinput):
    numbers = float(input("What are the numbers? "))
    i += numbers
average = i/numberinput
print("The average of the numbers in your list is " + str(average))
    
# #5:
length = int(input("Enter the length of the rectangular prism: "))
width = int(input("Enter the width of the rectangular prism: "))
height = int(input("Enter the height of the rectangular prism: "))
def rectPVolume(l,w,h):
     v = l * w * h
     return v
volume = rectPVolume(length,width,height)
print("The volume of the rectangular prism is " + str(volume))

# #6:
num1 = input("What's your first number? ")
num2 = input("What's your second number? ")
num3 = input("What's your third number? ")
def maximum(num1,num2,num3):
    total=max(num1, num2, num3)
    return total
print("Your max number is: ")
print maximum(num1,num2,num3)

# #7:
def star(rows):
    for j in range(rows-1,0,-1):
        print(''*(rows-j-1)+'* '*(j+1))
    for i in range(rows):
        print (''*(rows-i-1)+'* '*(i+1))
star(2)

# #8:
numlist = []
lessthan = []
numberinput = int(input("How many numbers are there: "))
for i in range(1, numberinput + 1):
    value = int(input("Enter value %d here: " %i))
    numlist.append(value)
for j in range(numberinput):
    if(numlist[j] < 10):
        lessthan.append(numlist[j])
print("The number(s) in your list that are less than 10 are: " + str(lessthan))

# #9:
def fibo(n):
    i = 1
    fibo = [1,1]
    while i < n:
        fibo.append(fibo[i] + fibo[i - 1])
        i = i + 1
    print(fibo)
nums = input("How many numbers in the Fibbonaci squence would you like to generate? ")
fibo(nums - 1)

#10:
def speedtest(speed):
    if speed <= 75:
        print "Ok"
    elif speed > 75:
        points=(speed/5)-15
        if points< 12:
            print ("You have " + str(points) + " points, please drive slower.")
        elif points> 12:
            print str("You have " + str(points) + " points, your license has been suspended.")
    return speed
speedtest(85)

Each new term of the fibonacci sequence is generated by adding the previous 2 terms
By considering the terms in the sequence that do not exceed 4 million, find the sum of the even numbered terms in the sequence

def fibo(n):
    i = 1
    fibo = [1,1]
    while i < n:
        fibo.append(fibo[i] + fibo[i - 1])
        i = i + 1
    print(fibo)
nums = input("How many numbers in the Fibbonaci squence would you like to generate? ")
fibo(nums - 1)
sum = fibo + 2

a, b = 1, 1
total = 0
while a <= 4000000:
    if a % 2 == 0:
        total += a
    a, b = b, a+b  
print total
